plugins:
  zendesk_plugin_enabled:
    default: false
    client: true
  zendesk_base_url:
    default: "https://yourorganization.zendesk.com"
    client: false
  zendesk_username:
    default: "username"
    client: false
  zendesk_password:
    default: "password"
    client: false
  zendesk_requester_id:
    default: "ID of Zendesk Requester/Agent (Optional)"
    client: false
