plugins:
  zendesk_plugin_enabled:
    default: true
    client: true
  zendesk_base_url:
    default: "https://yourorganization.zendesk.com"
    client: true
  zendesk_email:
    default: "email"
    client: false
  zendesk_password:
    default: "password"
    client: false
